#!/bin/bash

TANGO_HOST=@TANGO_HOST@
INSTANCE=@INSTANCE_NAME@
VERSION=@VERSION@
WD=/home/p05user/HeadQuarter
MONGODB_HOST=localhost

echo TANGO_HOST=$TANGO_HOST
echo INSTANCE=$INSTANCE
echo VERSION=$VERSION
echo MONGODB_HOST=$MONGODB_HOST
echo Using Java:
echo `java -version`

XMX=1G
echo XMX=$XMX

JAVA_OPTS="-server -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5339 -Dcom.sun.management.jmxremote.port=3339 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Xmx$XMX -Xshare:off -XX:+UseG1GC -server -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=$WD/mtango.hprof -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -Xloggc:$WD/mtango.loggc -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=3"
echo JAVA_OPTS=$JAVA_OPTS

JAVA_ARGS="-DLOG_HOME=/var/tmp/ds.log -Dlogback.configurationFile=$WD/config/logback.xml -DLOG_LEVEL=ERROR -DTANGO_HOST=$TANGO_HOST -Dmongodb.host=$MONGODB_HOST"
echo JAVA_ARGS=$JAVA_ARGS

/usr/bin/java $JAVA_OPTS $JAVA_ARGS -jar $WD/HeadQuarter-$VERSION.jar $INSTANCE HeadQuarter $INSTANCE &> HeadQuarter.out &